#include <jni.h>
#include <Python.h>

#include "jpy_module.h"
#include "jpy_jtype.h"
#include "jpy_jobj.h"
#include "jpy_conv.h"



// Note code in this file is formatted according to the header generated by javah. This makes it easier
// to follow up changes in the header.

/*
 * Class:     org_jpy_python_PyLib
 * Method:    isInitialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jpy_python_PyLib_isInitialized
  (JNIEnv* jenv, jclass jLibClass)
{
    int retCode;
    retCode = Py_IsInitialized();
    printf("Java_org_jpy_python_PyLib_isInitialized: retCode=%d\n", retCode);
    return retCode != 0;
}

/*
 * Class:     org_jpy_python_PyLib
 * Method:    initialize
 * Signature: ([Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jpy_python_PyLib_initialize
  (JNIEnv* jenv, jclass jLibClass, jobjectArray jOptions, jboolean debug)
{
    printf("Java_org_jpy_python_PyLib_initialize: debug=%d\n", debug);
    if (!Py_IsInitialized()) {
        //Py_SetProgramName("java");
        Py_Initialize();
    }
    JPy_SetDebug(debug);
    if (JPy_Module == NULL) {
        PyObject* pyModule;

        pyModule = PyImport_ImportModule("jpy");
        if (pyModule == NULL) {
            printf("Java_org_jpy_python_PyLib_initialize: pyModule == NULL :-(\n");
            // todo: throw exception from last python error
            return JNI_FALSE;
        }
    }
    return JNI_TRUE;
}
  

/*
 * Class:     org_jpy_python_PyLib
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jpy_python_PyLib_destroy
  (JNIEnv* jenv, jclass jLibClass)
{
    printf("Java_org_jpy_python_PyLib_destroy called\n");
    if (Py_IsInitialized()) {
        Py_Finalize();
    }
}

/*
 * Class:     org_jpy_python_PyLib
 * Method:    execScript
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT void JNICALL Java_org_jpy_python_PyLib_execScript
  (JNIEnv* jenv, jclass jLibClass, jstring jScript)
{
    const char* scriptChars;
    int retCode;

    scriptChars = (*jenv)->GetStringUTFChars(jenv, jScript, NULL);
    printf("Java_org_jpy_python_PyLib_execScript: script='%s'\n", scriptChars);
    retCode = PyRun_SimpleString(scriptChars);
    (*jenv)->ReleaseStringUTFChars(jenv, jScript, scriptChars);
    if (retCode < 0) {
        // todo: throw
    }
}


/*
 * Class:     org_jpy_python_PyLib
 * Method:    decref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jpy_python_PyLib_decref
  (JNIEnv* jenv, jclass jLibClass, jlong objId)
{
    printf("Java_org_jpy_python_PyLib_decref: objId=%p\n", (PyObject*) objId);
    Py_DECREF((PyObject*) objId);
}


/*
 * Class:     org_jpy_python_PyLib
 * Method:    getIntValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jpy_python_PyLib_getIntValue
  (JNIEnv* jenv, jclass jLibClass, jlong objId)
{
    PyObject* pyObject;
    pyObject = (PyObject*) objId;
    return PyLong_AsLong(pyObject);
}

/*
 * Class:     org_jpy_python_PyLib
 * Method:    getDoubleValue
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_jpy_python_PyLib_getDoubleValue
  (JNIEnv* jenv, jclass jLibClass, jlong objId)
{
    PyObject* pyObject;
    pyObject = (PyObject*) objId;
    return PyFloat_AsDouble(pyObject);
}

/*
 * Class:     org_jpy_python_PyLib
 * Method:    getStringValue
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jpy_python_PyLib_getStringValue
  (JNIEnv* jenv, jclass jLibClass, jlong objId)
{
    PyObject* pyObject;
    jstring jString;

    pyObject = (PyObject*) objId;

    if (JPy_ConvertPythonToJavaString(jenv, pyObject, &jString) < 0) {
        // todo throw exception from last error...
        return NULL;
    }

    return jString;
}

/*
 * Class:     org_jpy_python_PyLib
 * Method:    getObjectValue
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_jpy_python_PyLib_getObjectValue
  (JNIEnv* jenv, jclass jLibClass, jlong objId)
{
    PyObject* pyObject;
    jobject jObject;

    pyObject = (PyObject*) objId;

    if (JObj_Check(pyObject)) {
        jObject = ((JPy_JObj*) pyObject)->objectRef;
    } else {
        if (JPy_ConvertPythonToJavaObject(jenv, pyObject, &jObject) < 0) {
            // todo throw exception from last error...
            return NULL;
        }
    }

    return jObject;
}


/*
 * Class:     org_jpy_python_PyLib
 * Method:    getModule
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jpy_python_PyLib_importModule
  (JNIEnv* jenv, jclass jLibClass, jstring jName)
{
    PyObject* pyName;
    PyObject* pyModule;
    const char* nameChars;

    nameChars = (*jenv)->GetStringUTFChars(jenv, jName, NULL);
    printf("Java_org_jpy_python_PyLib_getModule: name='%s'\n", nameChars);
    pyName = PyUnicode_FromString(nameChars);
    pyModule = PyImport_Import(pyName);
    /* pModule is a new reference */
    Py_DECREF(pyName);
    (*jenv)->ReleaseStringUTFChars(jenv, jName, nameChars);
    return (jlong) pyModule;
}


/*
 * Class:     org_jpy_python_PyLib
 * Method:    getAttributeValue
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jpy_python_PyLib_getAttributeValue
  (JNIEnv* jenv, jclass jLibClass, jlong objId, jstring name)
{
    PyObject* pyObject;
    PyObject* pyValue;
    const char* nameChars;

    pyObject = (PyObject*) objId;

    nameChars = (*jenv)->GetStringUTFChars(jenv, name, NULL);
    printf("Java_org_jpy_python_PyLib_getAttributeValue: objId=%p, name='%s'\n", pyObject, nameChars);
    pyValue = PyObject_GetAttrString(pyObject, nameChars);
    /* pyValue is a new reference */
    (*jenv)->ReleaseStringUTFChars(jenv, name, nameChars);
    return (jlong) pyValue;
}


/*
 * Class:     org_jpy_python_PyLib
 * Method:    setAttributeValue
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_jpy_python_PyLib_setAttributeValue
  (JNIEnv* jenv, jclass jLibClass, jlong objId, jstring jName, jobject jValue, jclass jValueClass)
{
    PyObject* pyObject;
    const char* nameChars;
    PyObject* pyValue;
    JPy_JType* valueType;

    pyObject = (PyObject*) objId;

    nameChars = (*jenv)->GetStringUTFChars(jenv, jName, NULL);
    printf("Java_org_jpy_python_PyLib_setAttributeValue: objId=%p, name='%s', jValue=%p, jValueClass=%p\n", pyObject, nameChars, jValue, jValueClass);

    if (jValue != NULL && jValueClass == NULL) {
        jValueClass = (*jenv)->GetObjectClass(jenv, jValue);
    }

    printf("Java_org_jpy_python_PyLib_setAttributeValue: 1\n");

    if (jValueClass != NULL) {
        valueType = JType_GetType(jenv, jValueClass, JNI_FALSE);
        if (valueType == NULL) {
            printf("Java_org_jpy_python_PyLib_setAttributeValue: 1a\n");
            // todo: create exception from last error
            goto error;
        }
    } else {
            printf("Java_org_jpy_python_PyLib_setAttributeValue: 1b\n");
        valueType = NULL;
    }
            printf("Java_org_jpy_python_PyLib_setAttributeValue: 2\n");

    if (jValue != NULL && valueType != NULL) {
        pyValue = JType_ConvertJavaToPythonObject(jenv, valueType, jValue);
            printf("Java_org_jpy_python_PyLib_setAttributeValue: 2a\n");
        if (pyValue == NULL) {
            // todo: create exception "Java object not convertible: "  + last Python error msg
            goto error;
        }
    } else {
            printf("Java_org_jpy_python_PyLib_setAttributeValue: 2b\n");
        pyValue = Py_BuildValue("");
    }

            printf("Java_org_jpy_python_PyLib_setAttributeValue: 3\n");
    if (PyObject_SetAttrString(pyObject, nameChars, pyValue) < 0) {
        // todo: create exception from last error
    }

error:
            printf("Java_org_jpy_python_PyLib_setAttributeValue: 4\n");
    (*jenv)->ReleaseStringUTFChars(jenv, jName, nameChars);
    // todo: on error, throw Java exception
}


/*
 * Class:     org_jpy_python_PyLib
 * Method:    call
 * Signature: (JZLjava/lang/String;I[Ljava/lang/Object;[Ljava/lang/Class;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jlong JNICALL Java_org_jpy_python_PyLib_call
  (JNIEnv *jenv, jclass jLibClass, jlong objId, jboolean isMethodCall, jstring jName, jint argCount, jobjectArray jArgs, jobjectArray jParamClasses)
{
    PyObject* pyObject;
    PyObject* pyCallable;
    PyObject* pyArgs;
    PyObject* pyArg;
    PyObject* pyReturnValue;
    PyObject* pyMethod;
    const char* nameChars;
    jint i;
    jobject jArg;
    jclass jParamClass;
    JPy_JType* paramType;

    pyObject = (PyObject*) objId;

    nameChars = (*jenv)->GetStringUTFChars(jenv, jName, NULL);

    printf("Java_org_jpy_python_PyLib_call: objId=%p, name='%s', argCount=%d\n", pyObject, nameChars, argCount);

    pyArgs = NULL;

    // Note: pyCallable is a new reference
    pyCallable = PyObject_GetAttrString(pyObject, nameChars);
    if (pyCallable == NULL) {
        // todo: create Java exception "function or method not found: " + nameChars
        printf("Java_org_jpy_python_PyLib_call: function or method not found: '%s'\n", nameChars);
        goto error;
    }

    if (!PyCallable_Check(pyCallable)) {
        // todo: create exception "object is not callable: " + nameChars
        printf("Java_org_jpy_python_PyLib_call: object is not callable: '%s'\n", nameChars);
        goto error;
    }

    pyArgs = PyTuple_New(argCount);
    for (i = 0; i < argCount; i++) {
        jArg = (*jenv)->GetObjectArrayElement(jenv, jArgs, i);

        if (jParamClasses != NULL) {
            jParamClass = (*jenv)->GetObjectArrayElement(jenv, jParamClasses, i);
        } else {
            jParamClass = (*jenv)->GetObjectClass(jenv, jArg);
        }

        printf("Java_org_jpy_python_PyLib_call: 1 i=%d\n", i);

        paramType = JType_GetType(jenv, jParamClass, JNI_FALSE);
        if (paramType == NULL) {
            // todo: create exception from last error
            goto error;
        }

        printf("Java_org_jpy_python_PyLib_call: 2 i=%d\n", i);

        pyArg = JType_ConvertJavaToPythonObject(jenv, paramType, jArg);
        if (pyArg == NULL) {
            // todo: create exception "argument "+(i+1)+" not convertible: "  + last Python error msg
            goto error;
        }

        printf("Java_org_jpy_python_PyLib_call: 3 i=%d\n", i);

        // pyArg reference stolen here
        PyTuple_SetItem(pyArgs, i, pyArg);
    }

    if (isMethodCall) {
        pyMethod = PyMethod_New(pyCallable, pyObject);
        if (pyMethod == NULL) {
            // todo: create out of memory exception
            goto error;
        }
        Py_DECREF(pyCallable);
        pyCallable = pyMethod;
    }

    printf("Java_org_jpy_python_PyLib_call: 4\n");
    pyReturnValue = PyObject_CallObject(pyCallable, pyArgs);
    if (pyReturnValue == NULL) {
    printf("Java_org_jpy_python_PyLib_call: 4a\n");
        // todo: create exception "argument "+(i+1)+" not convertible: "  + last Python error msg
        goto error;
    }
    printf("Java_org_jpy_python_PyLib_call: 4b\n");

    Py_INCREF(pyReturnValue);

error:
    printf("Java_org_jpy_python_PyLib_call: 5\n");
    (*jenv)->ReleaseStringUTFChars(jenv, jName, nameChars);
    Py_DECREF(pyCallable);
    Py_DECREF(pyArgs);

    // todo: on error, throw Java exception

    return (jlong) pyReturnValue;
}
