/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jpy_python_PyLib */

#ifndef _Included_org_jpy_python_PyLib
#define _Included_org_jpy_python_PyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jpy_python_PyLib
 * Method:    isInterpreterInitialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jpy_python_PyLib_isInterpreterInitialized
  (JNIEnv *, jclass);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    initializeInterpreter
 * Signature: ([Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jpy_python_PyLib_initializeInterpreter
  (JNIEnv *, jclass, jobjectArray, jboolean);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    destroyInterpreter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jpy_python_PyLib_destroyInterpreter
  (JNIEnv *, jclass);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    execScript
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_jpy_python_PyLib_execScript
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    decref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jpy_python_PyLib_decref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    getIntValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jpy_python_PyLib_getIntValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    getDoubleValue
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_jpy_python_PyLib_getDoubleValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    getStringValue
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jpy_python_PyLib_getStringValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    getObjectValue
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_jpy_python_PyLib_getObjectValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    importModule
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jpy_python_PyLib_importModule
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    getAttributeValue
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jpy_python_PyLib_getAttributeValue
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    setAttributeValue
 * Signature: (JLjava/lang/String;Ljava/lang/Object;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_jpy_python_PyLib_setAttributeValue
  (JNIEnv *, jclass, jlong, jstring, jobject, jclass);

/*
 * Class:     org_jpy_python_PyLib
 * Method:    call
 * Signature: (JZLjava/lang/String;I[Ljava/lang/Object;[Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_org_jpy_python_PyLib_call
  (JNIEnv *, jclass, jlong, jboolean, jstring, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
